### ISSUE TITLE
It does not work for polygons.

### ISSUE THREAD

**Issue by igor-mikushkin** [Klowner/inkscape-applytransforms#2]
Steps to reproduce:
1. Select polygon containing translate transform,
2. Start Apply Transforms.

Expected result:
1. Polygon position is the same as before applying transforms,
2. Polygon does not contain transforms now.

Actual result:
1. Transform is removed,
2. Points contain old values,
3. Polygon is moved in result.

Environment:
Windows 10, Inkscape 0.92.1.

**Comment by mmuman** [comment]
I just wrote a fix for this.
I wanted to add town labels on an SVG map of a french district but the text ended up way too large and I noticed there was a transform on the main group, so I tried this extension and it failed because all but one town are polygon objects...
Now I get the polygons to stick at the correct location with the transform applied, but the only town drawn with a path ends up with a page-wide white background that covers half of the rest...

**Comment by Klowner** [comment]
Awesome, @mmuman. I'd be happy to look at your changes if you'd like. Also pull requests are welcome!

**Comment by mmuman** [comment]
Sure, just need to sort this path bug out.

**Comment by mmuman** [comment]
Hmm, ok looks like the path bug is unrelated, the boggus object has its own transform matrix so the merging is probably broken.

**Comment by mmuman** [comment]
Ohh, I just found out the issue with the remaining path objects.
They both have a "stroke-width:2.00536966" style, that doesn't get updated.
So in the new coordinates 2.0 is so large that it strokes the whole page with the border color.

**Comment by Klowner** [comment]
Oh awesome, good find. We could scale the stroke width by the transform
scale maybe

**Comment by mmuman** [comment]
I suppose so.
I'd add checks for unhandled things, like "warning: object specifies a class which can add styling that won't be transformed correctly"

**Comment by mmuman** [comment]
Ok, now with #4 it works-for-me™.
Except that the file has a non-uniform canvas scale for some weird reason, and the font looks ugly then.
Wondering if this could be changed to a transform matrix and applied as well in any way...
